### ISSUE TITLE
`createArrayWith` length does not override `arrayOfFixture` count

### ISSUE THREAD

**Issue by christinachimi** [jcteague/efate#125]
I have a fixture that uses `arrayOfFixture` for one of its properties. In general I don't want or need to specify a count, so the fixture itself does not have one. Sometimes I want to limit this to only create a one-item array, but it seems that the length I pass to `createArrayWith` doesn't override the default count of 3.

```
interface Bar {
  id: number
}
interface Foo {
  bars: Bar[]
}

const barFixture = createFixture<Bar>((b) => {
  b.id.asNumber()
})

const fooFixture = createFixture<Foo>((f) => {
  f.bars.arrayOfFixture({ fixture: barFixture })
})
```

I want to be able to do 

```
const myFoo = fooFixture.create({
  bars: barFixture.createArrayWith(1)
})
```

and get something that looks like

```
{
   bars: [{ id: 1}]
}
```

but instead I end up with 

```
{
   bars: [{ id: 1}, { id: 3}, { id: 4}]
}
```

Is this possible with the current feature set?

**Comment by jcteague** [comment]
Oh, I see.  Have you tried setting the count parameter?
```
const fooFixture = createFixture<Foo>((f) => {
  f.bars.arrayOfFixture({ fixture: barFixture, count: 1 })
})
```

**Comment by christinachimi** [comment]
Yes, `arrayOfFixture` in the `createFixture` call works as expected when you pass count. In my case, most of the time I don't want to limit this to just 1 (but in this particular case I do). It's just unexpected that when you try to override `bars` with `createArrayWith`, that you still get a length of 3. Maybe not a bug but an unexpected behavior.

I am on version `1.5.0`.

**Comment by jcteague** [comment]
okay, I'm following now.  I'll take a look.

Thanks

**Comment by christinachimi** [comment]
(Thank you for this library, by the way, it's been very helpful.)

**Comment by jcteague** [comment]
I had a versioning snafu, but 1.5.1 should fix the issue.

Thanks for bringing this to my attention.
