### ISSUE TITLE
Object created lost its constructor

### ISSUE THREAD

**Issue by Charly-xepelin** [jcteague/efate#132]
The following example shows that the object created by the fixture factory does not carry object type identity.

```typescript
import { defineFixture } from 'efate';

class Sample {
  constructor(public type: string) {}
}

describe('fixture', () => {
  it('should create object with type', () => {
    const sampleFixture = defineFixture<Sample>(t => {
      t.type.asString();
    });

    const sample = sampleFixture.create();

    expect(sample).toBeInstanceOf(Sample);
  });
});

```

The result got was:

```
Error: expect(received).toBeInstanceOf(expected)

Expected constructor: Sample
Received constructor: Object

```

Perhaps it can be fixed by manually setting the constructor to NewClass
```typescript
Object.setPrototypeOf(obj, NewClass.prototype);
(obj as any).constructor = NewClass;
```

The problem is in the line:
```typescript
    const fixture = {} as T;
```
of https://github.com/jcteague/efate/blob/master/packages/efate/src/fixture.ts

**Comment by jcteague** [comment]
Thanks for bringing this to my attention.  What is the use case for needing this.  I generally just use typescript types and interfaces as the the parameter, so I'd have to look into this some more.

**Comment by jcteague** [comment]
@Charly-xepelin I have some misgivings about this.  While it might seem that the return type should be an instance of the type you pass as a generic parameter, it's not.  It's an object that has all of the fields that you have defined in the with the builder.  The generic parameter on `defineFixture` is really there just to help you with autocomplete of the fields that you want to include on the fixture.

There is nothing stopping you from adding fields that are not part of the type passed in, nor are you required to define field definitions of every property.

Casting the fixture as `T` is probably a mistake and I should be inferring the type from the properties that I've added to the fixture object.  I'll certainly look into that.

To say that the fixture is truly an instance of an object would not always be correct for all cases, it would be up to the implementor.

That being said, I can see use cases where you'd want it to be an instance of a class.  I would certainly entertain a PR that adds this functionality, provided it's something that you would optionally add as part of the fixture definition.

A short term fix would be not to export the `sampleFixture` directly, but instead put the create behind your own function where you've set the object prototype on the fixture.

**Comment by Charly-xepelin** [comment]
Thanks @jcteague for your comments. The use case is to generate sample Commands, Queries, or Events. The CQRS logic dispatch to command/query/event handlers by object class (object constructor).

For example you have:

```ts
class CreateUserCommand extends ICommand {
   constructor(public readonly name, public lastname);
}

// in dispatch logic
class SomeCommandHandler {
  //  ...
  handle(cmd: ICommand) {
     if (cmd instanceof CreateUserCommand) { // Here it will fail if the object is not initialized with the correct constructor
        this.handleCreateUserCommand(cmd);
     }
     // ...
  }

  private handleCreateUserCommand(cmd: CreateUserCommand) {
     // ...
  }
}
```
 
I started using a different approach to create Commands, using the zod library, so the command constructor now receives an object with properties. In this case I can use efate without problem.

I face the problem with the first design and I think it can be a plus to this excellent library.

**Comment by jcteague** [comment]
Yeah, I assumed you needed for `instanceof` checks.  I'll have to do some testing around changing the prototype. 

Zod sounds like a good approach.  Have you considered using Typescript [type-guards](https://www.typescriptlang.org/docs/handbook/advanced-types.html#type-guards-and-differentiating-types)?

**Comment by Charly-xepelin** [comment]
AFAIK type guards are limited to native types. All classes will report "object" for its type.

**Comment by jcteague** [comment]
It sounds like you've got another solution so you probably don't need it, but to clarify that's not correct.  Type guards can be used to verify the type and they can also be used at runtime.

using the example from the docs:
```TypeScript
function isFish(pet: Fish | Bird): pet is Fish {
  return (pet as Fish).swim !== undefined;
}
```
Using this type guard to check an object, Typescript will know it's a `Fish` object after a conditional test:
```TypeScript
let pet = getSmallPet();
 
if (isFish(pet)) {
  //pet will be considered to be of type Fish in this block
}
  ```
