### ISSUE TITLE
Add mention on how to enable debugger logs

### ISSUE THREAD

**Issue by micalevisk** [jcteague/efate#90]
I found that we can use the env var `DEBUG=efate:fixture*` to display logs that could help us on debugging `efate`. Could you please mention that on `packages/efate/README.md`?

https://github.com/jcteague/efate/blob/7e5d73363de5821f79e6d5b765696a25afc08880/packages/efate/src/fixture.ts#L7

**Comment by jcteague** [comment]
@micalevisk 👍 done!
